# Generated by Django 3.0.3 on 2020-02-25 02:00

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('url', models.URLField(default='http://www.rcc.com', verbose_name='个人主页')),
                ('email', models.EmailField(default='1326729135@qq.com', max_length=254, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('body', models.CharField(max_length=100, verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
