# Generated by Django 3.0.3 on 2020-02-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200225_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
