# Generated by Django 3.0.3 on 2020-02-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_yes', models.CharField(default=0, max_length=5)),
                ('op_no', models.CharField(default=0, max_length=5)),
                ('op_verno', models.CharField(default=0, max_length=5)),
                ('op_verv', models.CharField(default=0, max_length=5)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Vote')),
            ],
        ),
    ]
