# Generated by Django 3.0.3 on 2020-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='op_no',
        ),
        migrations.RemoveField(
            model_name='option',
            name='op_verno',
        ),
        migrations.RemoveField(
            model_name='option',
            name='op_yes',
        ),
        migrations.AddField(
            model_name='option',
            name='content',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
