# Generated by Django 3.0.3 on 2020-02-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200216_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=0, max_length=20)),
                ('op_verv', models.CharField(default=0, max_length=5)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Vote')),
            ],
        ),
    ]
