# Generated by Django 3.0.3 on 2020-02-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_option1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='op_verv',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='option1',
            name='op_verv',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='vote',
            name='message',
            field=models.CharField(max_length=20, verbose_name='投票问题'),
        ),
    ]
